### ISSUE TITLE
"computer says no"

### ISSUE THREAD

**Issue by badcop666** [santiagobasulto/slack-cli#1]
$ python --version
Python 3.7.0

Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\slack.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'main'

**Comment by josuebasurto** [comment]
I think similar is happening to me.
 
```
C:\Users\Josh>slack -a happyhappyhappyhappyhappyhappyhappytoken auth_test
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\slack.exe\__main__.py", line 5, in <module>
ImportError: No module named main
C:\Users\Josh>_
```

Python 2.7.15

**Comment by josuebasurto** [comment]
Worked cloning and running locally
```
 python main.py --token xoxp-happyhappyhappyhappyhappyhappyhappytoken auth_test
... OK ...
Team      : Awesome Slack Team - (INTERNAL SLACK ID)
URL       : https://awesomeslackteam.slack.com/
User      : josh - (MY ID)
```

😀 

Hope this helps @badcop666

**Comment by santiagobasulto** [comment]
Project will be archived.
