### ISSUE TITLE
issue with `channels.list`

### ISSUE THREAD

**Issue by pedro380085** [santiagobasulto/slack-cli#5]
==== Deleting Channels ====
Traceback (most recent call last):
  File "/usr/local/bin/slack", line 8, in <module>
    sys.exit(main())
  File "/usr/local/bin/main.py", line 92, in main
    slack(obj={})
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/bin/main.py", line 88, in channels
    cmd.execute()
  File "/usr/local/lib/python3.9/site-packages/slack_cli/cmd.py", line 104, in execute
    for idx, channel in enumerate(self.channels):
  File "/usr/local/lib/python3.9/site-packages/slack_cli/api.py", line 80, in channels
    resp = self.__request('channels.list', **kwargs)
  File "/usr/local/lib/python3.9/site-packages/slack_cli/api.py", line 70, in __request

**Comment by rjhilgefort** [comment]
I'm seeing this as well

**Comment by santiagobasulto** [comment]
The method `channel.list` has been deprecated and the new one is: `conversations.list`. But the delete method is also deprecated, so there's no way around these issues for now.

I'll archive this project as it's no longer working.
